### ISSUE TITLE
Update icon to be awesome

### ISSUE THREAD

**Issue by lexitorres** [lexitorres/Android#1]
Icon should be awesome

**Comment by alice-default** [comment]
@lexitorres could you mention me in this issue? I want to test the "unanswered by me" option in codetree. Wondering if issues show up when i've been mentioned

**Comment by lexitorres** [comment]
sure thing done @alice-default

**Comment by alice-default** [comment]
@lexitorres testing

**Comment by lexitorres** [comment]
replying but not mentioning

**Comment by lexitorres** [comment]
This needs #2 to go - @alice-default can you take a look?
